name: radhaakrishan
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^0.1.15

msix_config:
  display_name: Radha Krishan
  publisher_display_name: Parth Aggarwal
  identity_name: frazile.fz.radhakrishan
  msix_version: 1.0.0.0
  # certificate_path: C:\<PathToCertificate>\<MyCertificate.pfx>
  # certificate_password: 1234 (require if using .pfx certificate)
  publisher: CN=Frazile Inc, O=Frazile Inc, L=New Delhi, S=Delhi, C=IN
  # logo_path: C:\<PathToIcon>\<Logo.png>
  # start_menu_icon_path: C:\<PathToIcon>\<Icon.png>
  # tile_icon_path: C:\<PathToIcon>\<Icon.png>
  # vs_generated_images_folder_path: C:\<PathToFolder>\Images
  icons_background_color: "#ffffff"
  architecture: x64
  capabilities: "internetClient,location"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
